### ISSUE TITLE
 [RA2 RC2] Update to K8s 1.25

### ISSUE THREAD

**Issue by rgstori** [anuket-project/anuket-specifications#3085]
@collivier does RC2 plan to use 1.25 for Nile?

1.25 out on 23rd August 22
1.26 should be out end of December 22 (after Nile)

**Comment by rgstori** [comment]
Update to K8s version -
decision to go with 1.24 as EoS will be 28th July 2023, and by then we plan to publish the Anuket Orinoco release (Nile+1, with e.g. k8s 1.26)

Decision is due to industry generally being on much older releases than Anuket ones

**Comment by rgstori** [comment]
update index, check bottom of ch3, check whole ch4, api and features in ch6, ch7 check huge pages

**Comment by collivier** [comment]
@rgstori This issue is incorrect. It falsy duplicates the one I created about v1.25
v1.25 is the clear target for Nile by Anuket/CNTT rules and by the Kubernetes maintenance window
(I thought it was planned on RA2 wiki – I will check your planning in first milestones).
And I would consider the changes introduced in v1.25 as equally important (e.g. API rules) here.

RC2 was just updated to v1.25

**Comment by collivier** [comment]
I don't see why it should be closed. I'm still concerned about this issues.
I still don't understand why Anuket should be deprecated when released even if some vendor products are late (if it's true).

@steelescotr now RC2 and RA2 are unsynced thanks to the last minutes' RA2 new release target.

**Comment by collivier** [comment]
BYW I reset the title " [RA2 RC2] Update to K8s 1.25" at it was
