### ISSUE TITLE
[pcac]: Think about using a different theme instead of material

### ISSUE THREAD

**Issue by CsatariGergely** [anuket-project/anuket-specifications#3191]
The material-sphinx theme is not actively maintained anymore and it has an open bug related to Anuket (https://github.com/bashtage/sphinx-material/issues/127).
We should think about selecting an other theme. Some of the themes are listed here: https://sphinx-themes.org/

**Comment by CsatariGergely** [comment]
#3212 Implements a pilot for the Alabaster theme for Sphinx. 

@collivier how can I try if Alabaster is correct where Material fails?

**Comment by CsatariGergely** [comment]
Themes with document level navigation plane: 
https://sphinx-themes.org/sample-sites/piccolo-theme/
https://sphinx-themes.org/sample-sites/furo/
https://sphinx-themes.org/sample-sites/sphinx-book-theme/
https://sphinx-themes.org/sample-sites/sphinx-documatt-theme/

**Comment by CsatariGergely** [comment]
Edit created a pilot for the Piccolo theme here: https://gerrit.opnfv.org/gerrit/c/opnfvdocs/+/73644

**Comment by EditKoselak** [comment]
> Edit created a pilot for the Piccolo theme here: https://gerrit.opnfv.org/gerrit/c/opnfvdocs/+/73644

First attempt of the Piccolo theme:
![image](https://user-images.githubusercontent.com/61583300/202432873-baa7f282-3147-4065-9d4e-4085b31b9ea2.png)


We used the default Piccolo theme as a base and changed the followings:
- Color of the top navigation bar
- Size and padding of the logo in the top navigation bar
- Margins of the main text
- Color of the links in the main text and in the navigation bars + the link hover color in the navigation bars. We choose the greenish color from the Anuket brand colors, since it works better in dark mode.

The default Piccolo color is still used in the search button and in the arrow next to the Page contents label. If the proposed theme is approved, we can change these settings as well.

**Comment by EditKoselak** [comment]
![image](https://user-images.githubusercontent.com/61583300/209103443-b8593f04-fe20-4855-827b-7b94625891cc.png)

The following updates have been done:

- changing the color of the search button
- changing the color of the Page contents label
- removing option to switch to dark mode
